project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - mp01.qmd
    - mp02.qmd
    - mp03.qmd
    - mp04.qmd
    - individual_report.qmd   

website:
  title: "STA 9750"
  description: "Course projects for STA 9750 at Baruch College"
  site-url: "https://shreyakarki71.github.io/STA9750-2025-FALL/"
  navbar:
    background: primary
    search: false
    left:
      - text: "Mini-Projects"
        menu:
          - text: "MP01"
            href: mp01.html
          - text: "MP02"
            href: mp02.html
          - text: "MP03"
            href: mp03.html
          - text: "MP04"
            href: mp04.html

      - text: "Course Project"
        href: individual_report.html

format:
  html:
    theme: minty
    toc: false

editor:
  mode: source


